Feat: Icons can be added in Input and button to see the password
balearesg/pragmate-ui pull request #42
Opened 2023-12-05 12:34 UTC by FranciscoSanvicente

# Feat: Icons can be added in Input and button

- Added the possibility of adding an icon to the Input component, these can be placed on the right or left, by default on the right, on the left by means of the left-icon class.

## Case: icon (default on the right)
```tsx
<Input  label="this is a label" icon="user" />
```
Result
<img width="211" alt="image" src="https://github.com/balearesg/pragmate-ui/assets/64644109/bf80bd8f-0c38-4a3f-9e93-51801b9877cd">

## Case: icon on the left
```tsx
<Input  label="this is a label" icon="user"  className="left-icon"/>
```
Result:
<img width="223" alt="image" src="https://github.com/balearesg/pragmate-ui/assets/64644109/fa8b1363-73ed-4ee8-8446-ad7f6fdd33b4">

- Added a button in the inputs of type password to see/hide the password, it will be by default in the inputs of type password.
  
## Case: password input
```tsx
<Input  label="this is a label" type="password" />
```
Result
<img width="212" alt="image" src="https://github.com/balearesg/pragmate-ui/assets/64644109/895d5607-c792-40fd-be0d-8923afe7995f">

##   Case: icon on the left with password input

```tsx
<Input  label="this is a label" icon="user"  className="left-icon" type="password" />
```
<img width="217" alt="image" src="https://github.com/balearesg/pragmate-ui/assets/64644109/2877c512-9b94-4ae1-ac01-392a61e4f72a">

## Case: Enter password with icon 

Result
```tsx
<Input  label="this is a label"   type="password" icon="user"/>
```
<img width="215" alt="image" src="https://github.com/balearesg/pragmate-ui/assets/64644109/2cbdf5fa-1cb0-4ec5-a140-5c42fcd692a2">

2023-12-05 15:39 UTC, jircdev requested changes

2023-12-05 15:39 UTC, jircdev commented on library/modules/alert/ts/alert.tsx
> +	console.log("🚀 ~ file: alert.tsx:8 ~ Alert ~ message:", message)
Please, remove any console.log to be able to integrate the PR.

2023-12-06 14:13 UTC, FranciscoSanvicente commented on library/modules/form/scss/input/icon/password.scss
> +        padding: 0.5rem 2rem 0.5rem 1rem;
@jircdev Seria para cualquier tipo de input

2023-12-06 14:34 UTC, FranciscoSanvicente commented
@jircdev 
Settings have been uploaded
Remove commented code
Remove console.log
Replace px with rem

2023-12-07 14:04 UTC, closed without merging