Fix: fixed code Checkbox / default empty value Input
balearesg/pragmate-ui pull request #51
Opened 2024-01-09 23:57 UTC by FranciscoSanvicente

# Fix: fixed code Checkbox

In the integration, an improvement in the Checkbox component was proposed, which were the following:

- Change in the names of the classes
- Remove inline styles
- Use custom properties

In the Input component the default value was changed from ' ' to ' ' because for security reasons, browsers do not allow to set a value different from ' ' (string without spaces) in file type inputs.

2024-01-10 01:24 UTC, jircdev requested changes

2024-01-10 01:24 UTC, jircdev commented on library/modules/form/controls/ts/checkbox/index.tsx
> +	let cls: string = `pragmate-checkbox ${className ? className : ''}`;
The class must be named "pui-". Please review it in any element.

2024-01-10 01:24 UTC, jircdev commented on library/modules/form/controls/ts/input/control.tsx
>  		placeholder: placeholder ?? ' ',
Please remove the blank space.

2024-01-10 01:24 UTC, jircdev commented on library/modules/form/controls/scss/checkbox.scss
>  .pragmate-checkbox {
the css class must be named "pui" following the standard defined @FranciscoSanvicente

2024-01-10 01:25 UTC, jircdev commented
@FranciscoSanvicente Did you manage "sizing" property for checkboxes ? Could be a good idea to manage different sizes like "xs", "sm" "lg". What do you think? like the inputs and other elements.

2024-01-10 15:36 UTC, FranciscoSanvicente commented
I think it is a good idea for the component but I would leave it for a future version.

2024-01-12 20:04 UTC, jircdev approved these changes

2024-01-12 20:05 UTC, merged